version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - super-heroes

volumes:
  pgdata:

networks:
  super-heroes:
    driver: bridge
